### PR TITLE
python3 shebang from #620

### PR DESCRIPTION
**Pull request by kpu**
### Description

This changes shebangs from `python` to the more explicit `python3` according to the patch in #620.  

The regression tests use `pip3` so `python3` is consistent with that.  

https://github.com/marian-nmt/marian-regression-tests/blob/6a08849b23f6c14eefbe12f4eb73dc638b962587/Makefile#L25

### CODE REVIEW

**Comment by snukky** [comment]
Thanks! Have you or @kdavis-mozilla tested these scripts with python3, especially scripts that are not used in regression tests? Have you checked if there are no scripts in regression tests that are mistakenly called via `python script.py` instead of just `./script.py`? If you already did it, I will not go over this again.

**Comment by kdavis-mozilla** [comment]
I'll run a set of tests later today to test this.

**Comment by kpu** [comment]
Also, I think the client works in python2.7 so we shouldn't force python3?

**Comment by kdavis-mozilla** [comment]
Python 3 is already required from the [Makefile](https://github.com/marian-nmt/marian-regression-tests/blob/master/Makefile#L25)

**Comment by snukky** [comment]
Yes, but there may be direct executions with python2 somewhere in the regression tests, and also not all scripts are used in regression tests. I will check.

**Comment by kpu** [comment]
The client script is intended to be usable outside the regression tests.  And many users don't care about running the regression tests.  So would a better way to be to change the tests (which assume `pip3` as @kdavis-mozilla points out) to invoke with `python3` rather than use the shebang?

**Comment by kdavis-mozilla** [comment]
I guess I'm just saying if you install the dependencies with pip3 for the tests they won't be available for python 2. So the tests have to use python 3 or they won't have the correct dependencies unless you get lucky.

**Comment by kpu** [comment]
Yeah I think the tests should always call python3. Which could be accomplished by always writing `python3 client_example.py` in the regression tests.

**Comment by snukky** [comment]
I think the issue is related rather to marian-regression-tests than marian-dev. I see `python xxx/model_info.py` in some regression tests, and if I remember correctly, this script generates different outputs for python2 and python3. I will take a look and unify this in the marian-dev/marian-regression-tests repo.

**Comment by emjotde** [comment]
@snukky I would put it on you to decide here.

**Comment by snukky** [comment]
I will clean up script executions in regression tests and then check if the rest of scripts works properly with python3. I am keeping the PR open.

**Comment by snukky** [comment]
I cleaned up calls to python in regression tests making sure that python3 is used everywhere (https://github.com/marian-nmt/marian-regression-tests/pull/51). This solved the issue reported by @kdavis-mozilla being motivation for reporting #620. 

The following scripts are used in regression tests and works fine with python3:
- contrib/model_info.py
- embeddings/export_embeddings.py
- server/client_example.py

Other scripts:
- checkpoints/average.py works with python3 
- scripts in embeddings/ seem to work too
- contrib/inject_ctt.py works
- I have not tested contrib/inject_model_params.py, but it should work. This script very unlikely is still compatible with the recent version of Nematus
- contrib/fix_hard.py has no shebang, but is definitely python2

Python 2 is no longer a default Python version in recent Ubuntu distros. It seems that `python` will not be available by default in Ubuntu 20.04 LTS, so it would be nice to update shebangs in our scripts.

**Comment by kpu** [comment]
> Following my last comment, I think it is good to have these updates. Could you add a note about the change in CHANGELOG.md?

Done.

**Pull request merged**
