### PR TITLE
compatibility with MS-internal Philly cluster

### PR DESCRIPTION
**Pull request by frankseide**
This PR contains changes to make Marian compatible with the Microsoft-internal compute cluster. It also has a few changes made on the way:

  * vocabularies can be read from flat files
  * comments of dimensions in `transformer.h`
  * word penalty parameter
  * logged losses are now normalized per target word

(Note: please ignore the list of commit comments below, as it includes several temporary changes that have been removed again.)

### CODE REVIEW

**Comment by emjotde** [comment]
Can you comment or show how the logging looks like now? Did you run regression tests with that?

**Comment by frankseide** [comment]
Logging now reports the Cost per word, for ce-mean, ce-sum, ce-mean-words, "times" the number of target labels that the Cost was measured on. This allows to compare progress of ce-sum runs across different minibatch sizes. The log now also shows the aggregate number of target labels processed so far, which makes it easier to compare runs that ended up using different MB size (the Epoch number only allows that at epoch boundaries). These changes are aimed at reducing mental math. I also increased the number of decimals for the Cost, as that allows direct comparison of runs that are expected to be identical. Example of logging:

```
[2018-03-19 20:09:23] Ep. 38 : Up. 193500 : Sen. 3129009 : Cost 2.97881484 * 13341033 after 5203488403 : Time 635.33s : 20998.72 words/s : L.r. 8.6266e-05
[2018-03-19 20:20:04] Ep. 38 : Up. 194000 : Sen. 3582181 : Cost 2.95717525 * 13717641 after 5217206044 : Time 641.33s : 21389.45 words/s : L.r. 8.6155e-05
[2018-03-19 20:30:11] Ep. 38 : Up. 194500 : Sen. 4017920 : Cost 3.00738382 * 13358969 after 5230565013 : Time 606.33s : 22032.40 words/s : L.r. 8.6044e-05
[2018-03-19 20:40:17] Ep. 38 : Up. 195000 : Sen. 4441780 : Cost 2.97530913 * 12928926 after 5243493939 : Time 605.95s : 21336.71 words/s : L.r. 8.5934e-05
```

**Comment by emjotde** [comment]
This will surely break a large number of our regression tests. Can we turn this into an option or solve this later with issue #195 ?

**Comment by emjotde** [comment]
Memo to self. Wait with pull for update.

**Pull request merged**
