### PR TITLE
Add GitHub workflow with CUDA 11 on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by snukky**
### Description
Building with CUDA 11.0 on Ubuntu 20.04 in our GitHub workflows. Without Boost because it's not pre-installed on the GitHub-hosted Ubuntu 20.04 image.

Added dependencies: none

### How to test
See GitHub Actions.

### Checklist

- [x] I have tested the code manually
- [ ] I have run regression tests (**not relevant**)
- [ ] I have read and followed CONTRIBUTING.md (**not relevant**)
- [ ] I have updated CHANGELOG.md (**not relevant**)

### CODE REVIEW

**Comment by emjotde** [comment]
@snukky this is just ready to merge, right?

**Comment by snukky** [comment]
Yes, it is ready. I am keeping it open for a while to have a chance to run it few times and see if there is some instability with Ubuntu 20.04/CUDA 11/GCC 9 as this image is a preview only. It looks fine so far.

**Comment by snukky** [comment]
So, it looked fine until now. We have already seen compilation failing due to that error (https://github.com/marian-nmt/marian-dev/pull/704/checks?check_run_id=1055063509). It is not related to the Marian code.

**Comment by snukky** [comment]
Answering https://github.com/marian-nmt/marian-dev/pull/660#issuecomment-684159713:
> Aren't the checks a necessary condition before merging? Now it allows me to merge despite the checks not having finished yet after my update? Should that not be a blocker?

It is not enabled yet. With distinct job names (done in the last commit here) it will be possible to select which checks are necessary. I will mark all but the Ubuntu 20.04 as required after merging this pull request.

**Comment by emjotde** [comment]
Approved. Feel free to merge when you see fit.

**Pull request merged**
