### PR TITLE
Port to CPU (~5 mo. out-of-date)

### PR DESCRIPTION
**Pull request by AngusL**
For open source release under the MIT license. I believe the current plan is to create a new port which draws on this one (especially kernels/tensor_operators.cpp, but perhaps also elsewhere e.g. DivNodeOp) for performance, rather than to literally rebase this branch on current master. A new port would still need to retain the Intel copyright header where appropriate (currently, any file we have created or modified).

(I would have this pull request target a new branch, but GitHub doesn't seem to support that.)

Edited 2018-02-16 to add: this is an Intel contribution, approved through the relevant internal process, and here I am acting in my role as an Intel employee.

### CODE REVIEW

**Comment by emjotde** [comment]
Great to see this. Thank you Angus and Sid! I will take a look at this over the next few days to come up with a way to bring adapt it to recent code.

**Comment by kpu** [comment]
Thank you!

**Comment by emjotde** [comment]
OK. After playing around with rebase, I think this is too complex. I am spending hours in merge conflicts that are not even affected by those changes. 

I will do this by hand and keep the intel copyright notices where it applies, if this is alright.

**Comment by emjotde** [comment]
Can the copyright be modified if Intel is still mentioned, i.e. adding myself and other contributors? It feels a bit weird to see only Intel's copyright notices on files I have written mostly myself, like expression_graph.h

**Comment by AngusL** [comment]
> Can the copyright notice be modified to add myself and other contributors?

Yes. Would something like the following work for you?

```
/* Contributions made by Intel Corporation:
 *   Copyright (C) 2017-2018 Intel Corporation
 *   SPDX-License-Identifier: MIT
 * 
 * [ ... any other individually named contributors ...]
 *
 * All other contributions:
 *   Copyright (C) [years] [contributor list]
 */
```

(Anything similar would also work, I just want to preserve our approval's prescribed header format.)

Also, I have edited the original comment, but for the avoidance of doubt: this is an Intel contribution, approved through the relevant internal process, and here I am acting in my role as an Intel employee.

**Comment by emjotde** [comment]
I will close this request as we have merged most of it manually. There are still a few things I have not quite brought over yet. I will try to add your fork as a branch to marian, to have your original code there. There is still a few things I want to look at.

**Pull request closed without merging**
