### PR TITLE
Warn if an unrecognized option is found in a config file

### PR DESCRIPTION
**Pull request by snukky**
The simplest solution for the missing warning mentioned in #315 that prints the message to the standard error stream. The warning message was there but not displayed because loggers cannot be initialized at that time.

### CODE REVIEW

**Comment by emjotde** [comment]
If it cannot be logged correctly, maybe it should be an abort?

**Comment by snukky** [comment]
Maybe, I have no opinion. Warning will allow to provide any config file you want, which might be useful during development.

**Comment by emjotde** [comment]
Lack of logging doesn't allow to track this down. Will an early abort be logged?

**Comment by snukky** [comment]
Yes, ABORT_IF will work here.

**Comment by emjotde** [comment]
Uhm, does the message from ABORT_IF get logged then? If yes, why would the previous message not get logged?

**Comment by emjotde** [comment]
Let's do ABORT then. I think it's logical to have that in the same vein as unrecognized options on the CLI also abort.

**Comment by snukky** [comment]
Replaced by #363

**Pull request closed without merging**
