### PR TITLE
Properly copy the entire vector in the int16_t case

### LINKED ISSUE #842: Jenkins marian-dev-cpu-avx2 #113 failed
Build 'marian-dev-cpu-avx2' is failing!

Last 50 lines of build output:

```
[...truncated 49.79 KB...]
[03/22/2021 16:05:33] Running setup script
[03/22/2021 16:05:33] Running tests/decoder/shortlist/test_shortlist_rnn_cpu.sh ... OK
[03/22/2021 16:05:44] Test took 00:00:10.898s
[03/22/2021 16:05:44] Checking directory: tests/decoder/wmt16
[03/22/2021 16:05:44] Running setup script
[03/22/2021 16:05:44] Running tests/decoder/wmt16/test_ende_cpu.sh ... OK
[03/22/2021 16:07:08] Test took 00:01:24.345s
[03/22/2021 16:07:08] Checking directory: tests/models/transformer
[03/22/2021 16:07:08] Running setup script
[03/22/2021 16:07:08] Running tests/models/transformer/test_hard_aligns_cpu.sh ... OK
[03/22/2021 16:07:20] Test took 00:00:12.199s
[03/22/2021 16:07:20] Checking directory: tests/models/wngt19
[03/22/2021 16:07:20] Running setup script
[03/22/2021 16:07:20] Running tests/models/wngt19/test_model_base_fbgemm_packed16.sh ... OK
[03/22/2021 16:07:36] Test took 00:00:15.199s
[03/22/2021 16:07:36] Running tests/models/wngt19/test_model_base_fbgemm_packed8.sh ... OK
[03/22/2021 16:07:49] Test took 00:00:13.363s
[03/22/2021 16:07:49] Checking directory: tests/models/wnmt18
[03/22/2021 16:07:49] Running setup script
[03/22/2021 16:07:49] Running tests/models/wnmt18/test_student_small.sh ... OK
[03/22/2021 16:08:03] Test took 00:00:13.465s
[03/22/2021 16:08:03] Running tests/models/wnmt18/test_student_small_aan.sh ... OK
[03/22/2021 16:08:14] Test took 00:00:11.422s
[03/22/2021 16:08:14] Running tests/models/wnmt18/test_student_small_aan_intgemm16.sh ... failed
[03/22/2021 16:08:25] Test took 00:00:11.111s
[03/22/2021 16:08:25] Running tests/models/wnmt18/test_student_small_aan_intgemm8.sh ... OK
[03/22/2021 16:08:35] Test took 00:00:10.057s
[03/22/2021 16:08:35] Checking directory: tests/scorer/scores
[03/22/2021 16:08:35] Running setup script
[03/22/2021 16:08:35] Running tests/scorer/scores/test_scores_cpu.sh ... OK
[03/22/2021 16:09:07] Test took 00:00:32.085s
[03/22/2021 16:09:07] Checking directory: tests/server
[03/22/2021 16:09:07] Running setup script
[03/22/2021 16:09:09] Running tests/server/test_ende_cpu.sh ... OK
[03/22/2021 16:09:49] Test took 00:00:39.791s
[03/22/2021 16:09:49] Checking directory: tests/training/restoring/multi-gpu
[03/22/2021 16:09:49] Running setup script
[03/22/2021 16:09:49] Running tests/training/restoring/multi-gpu/test_adam_sync_cpu.sh ... OK
[03/22/2021 16:10:25] Test took 00:00:36.222s
---------------------
Failed:
  - tests/decoder/intgemm/test_intgemm_16bit.sh
  - tests/models/wnmt18/test_student_small_aan_intgemm16.sh
Logs:
  - /var/lib/jenkins/workspace/marian-dev-cpu-avx2/regression-tests/tests/decoder/intgemm/test_intgemm_16bit.sh.log
  - /var/lib/jenkins/workspace/marian-dev-cpu-avx2/regression-tests/tests/models/wnmt18/test_student_small_aan_intgemm16.sh.log
---------------------
Ran 19 tests in 00:05:57.328s, 17 passed, 0 skipped, 2 failed
Build step 'Execute shell' marked build as failure

```

Changes since last successful build:
- [github] 096c48e51cd2e61bb275345d7cca99cbfd6bc5c7 - remove TC_MALLOC from optional dependencies (#840)

[View full output](http://vali.inf.ed.ac.uk/jenkins/job/marian-dev-cpu-avx2/113/)

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
### Description
Fixes #842 #843 #844

### Checklist

- [x] I have tested the code manually
- [x] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by emjotde** [comment]
Huh, so this is not about alignment after all?

**Review by emjotde — APPROVED** [review]

**Comment by emjotde** [comment]
@XapaJIaMnu Can you update the changelog and bump the version by one at the end?

**Comment by XapaJIaMnu** [comment]
Done

**Comment by emjotde** [comment]
Thanks!

**Comment by emjotde** [comment]
Waiting for compilation to finish and merging then.

**Pull request merged**
