### PR TITLE
Fix missing float template specialisation for elem::Plus

### PR DESCRIPTION
**Pull request by graemenail**
### Description
Template specialisations in `src/tensors/gpu/add_all.inc` have a `float` and `__half` variant. The corresponding `float` for an `elem::Plus`-based entry is missing.

Likely related #798. 

List of changes:
- Added float template specialisation to `add_all.inc`

Added dependencies: none

### How to test
In progress...

### Checklist

- [x] I have tested the code manually
- [ ] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
Can we merge this?

**Comment by graemenail** [comment]
I was waiting to run the regression tests, but the cluster is quite busy.

However, it's a small change - so if you're happy for it to be merged without that step then it's ready. 

I'll update the changelog.

**Review by snukky — APPROVED** [review]

**Comment by snukky** [comment]
I run the regression tests locally and they passed.

**Comment by graemenail** [comment]
Thanks @snukky

**Pull request merged**
