### PR TITLE
Merge quantization code with fp16 branch

### PR DESCRIPTION
**Pull request by emjotde**
### Description
This is meant to isolate the changes from PR https://github.com/marian-nmt/marian-dev/pull/690 (Quantized finetuning) into the fp16 training branch. Seems it might not have been too difficult.

@snukky can you work with @afaji and @kpu to verify this works? All the changes are basically your own changes, I only adapted `graph_group_sync.cpp`. Merge went through relatively smoothly.

### CODE REVIEW

**Comment by snukky** [comment]
This branch is not already with `--clip-norm 0`?

The quantized finetuning also needs hotfixes from #759 and #761, so I will pull them into this PR.

**Comment by emjotde** [comment]
It's not a PR into master, so does it matter?

**Comment by snukky** [comment]
The regression tests we already have for the quantized finetuning have been generated with the default `clip-norm 1` and the two hotfixes. The tests fail, so I wanted to make sure first what settings this branch uses.

**Comment by emjotde** [comment]
Ah, we should get rid of `--clip-norm x` then.

**Comment by emjotde** [comment]
@afaji @ykim362  Are you ever using `--clip-gemm x` in your quantized training? If not we can probably remove that? That was introduced by me and @kpu back in 2018 for WNGT, but probably never used again. Just clutter?

**Comment by ykim362** [comment]
@emjotde I don't use it. I am fine with removing it.

**Comment by kpu** [comment]
`--clip-gemm` has effectively been replaced by fitting to each tensor then @afaji's continued training

**Comment by emjotde** [comment]
Cool, happy to get rid of that soonish.

**Comment by snukky** [comment]
After applying the two Alham's hotfixes that are already in the master branch, the tests for quantized finetuning work. One test failed because this branch does not support continued training with `--after-batches` (i.e. the second run finished immediately due to `after: 20u,100u` in the config), but this is an irrelevant issue to this PR.

**Review by snukky — APPROVED** [review]

**Comment by snukky** [comment]
fp16.4 is in the internal repo, so this can be closed. Please re-open if something is left here.

**Pull request closed without merging**
