### PR TITLE
Update the way batch_flexible_lr is applied

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
This is more of Request for comment than a pull request. It compiles but it's not completely tested.

I have simplified the way batch-flexible-lr is applied, using an array of the size of devices to keep what the last number of words for this batch was.

We can move this code to the scheduler pretty much as it is by adding functions such as "scheduler_->SetbatchSize(batch, threadID)" and "scheduler->getLRforThread(threadID)" but it'd not really simplify the code further, it will just call the scheduler instead of doing the work directly. If you have other ideas, please suggest!.

### CODE REVIEW

**Comment by snukky** [comment]
Scheduler and TrainingState implement an observer pattern, so for SingletonGraph, I would propose something like the following:

1. add actAfterUpdate() (or actBeforeUpdate() if you wish) into TrainingObserver
2. implement this method in OptimizerBase
3. add newUpdate() into TrainingState
4. call newUpdate() before opt_->update() in SingletonGraph (through the scheduler)
5. implement logic in actBeforeUpdate() in Scheduler; use config options here
6. remove multiplyFactor_ from Optimizer, including update() methods which take it as an argument
7. remove scaleLearningRate_ and avgBatchWords_ from GraphGroup

This will require adding the size of the current batch into a TrainingState or passing it (or a Ptr<Batch>) into newUpdate and actBeforeUpdate.

For multiple workers, we would probably need multiple etas in TrainingState, and newUpdate and actBeforeUpdate methods should takes another argument indicating the ID of the worker.

**Comment by emjotde** [comment]
Multiple workers will always work in different threads. Make eta thread local instead of having multiple etas. Unless this is done already?

**Comment by XapaJIaMnu** [comment]
eta can't be thread_local because it's a class member... I can make it static and thread_local, but that feels wrong....

**Comment by XapaJIaMnu** [comment]
Hey,

Could you look at the second attempt. This only addresses the graphGroupSingleton case for now, I have not implemented the multigraph yet, requesting comments first.

Issues that I identify with this approach:
1) We can't do thread local in the member variables so we have to  arrays for each thread.
2) If this approach is to work with delayed updates, we need another scheduler call "ActAfterOptimizer", so that we know when an optimizer step has been performed and we can reset the counter of words seen so far, which would seem veeery clunky to me.

Is there another cleaner way to include this in the scheduler? This is what I understood from Roman's comments.

Cheers,

Nick

**Comment by emjotde** [comment]
@XapaJIaMnu could show something of this working in the end?

**Comment by XapaJIaMnu** [comment]
Hey,
Sorry for the late reply! I have done some parameter sweeps and I can say there's a small benefit of using flexible learning rate when the mini-batches are very imbalanced (eg --maxi-batch 100 together with a shallow model and a very large -w and --optimizer-delay). In the rest of the cases the variance between mini-batches is not that great.

**Comment by emjotde** [comment]
I will allow myself to close this without pulling then. We should probably remove the batch-flexible stuff then from master too?

**Pull request closed without merging**
