### PR TITLE
Add simple unit tests for binary files

### PR DESCRIPTION
**Pull request by emjotde**
### Description
Add a few unit tests for binary files

### Checklist

- [x] I have tested the code manually
- [ ] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by emjotde** [comment]
To be merged before https://github.com/marian-nmt/marian-dev/pull/825

**Comment by snukky** [comment]
Are these unit tests OS and CPU architecture independent?
They fail on Windows: https://github.com/marian-nmt/marian-dev/pull/826/checks?check_run_id=2028168848
If they are CPU dependent, we might need to make some expected outputs dependent on specific SIMD as we do in regression tests. We don't control what machine we get on Azure/GitHub DevOps.


> To be merged before #825

This is the opposite what is in #825, could you edit one of your messages?

**Comment by emjotde** [comment]
They write and read. I will try to test it on windows to see what is breaking there. Unless you have the possibility now to take a look.

**Review by snukky — APPROVED** [review]
The issue seemed to be TemporaryFile not working properly on Windows because of missing assignment of `file_`, which was not related to changes from the PR. After 3eca5ed, new unit tests pass.

**Pull request merged**
