### PR TITLE
remove most of cuda-syncs from AsyncGraphGroup

### PR DESCRIPTION
**Pull request by afaji**
issue #61

### CODE REVIEW

**Comment by XapaJIaMnu** [comment]
I am not entirely sure you need CudaChecks on memset or cudamemCPY (If the allocation went fine, surely you can access the memory). they wouldn't hurt, it's a matter of style I think.

I don't understand what happens with the CUDAStreamSyncronise stuff. Was it only relevant to your code?

**Comment by afaji** [comment]
CUDAStreamSync is either unnecessary of moved from the AsyncGraphGroup.h into the function that needs the sync. 

I initially added CUDA_CHECK thinking that your issue about lack of CUDA_CHECK was not resolved yet.

**Comment by afaji** [comment]
@emjotde Hi Marcin. Could you check on this? I just moved all cudaStreamSync outside graph_group.h

**Comment by afaji** [comment]
benchmark on 4 Titan Xs:
```
[2017-08-02 11:26:55] Ep. 1 : Up. 1000 : Sen. 79680 : Cost 153.89 : Time 156.07s : 12741.82 words/s
[2017-08-02 11:29:29] Ep. 1 : Up. 2000 : Sen. 159680 : Cost 125.15 : Time 153.48s : 13026.21 words/s
[2017-08-02 11:32:02] Ep. 1 : Up. 3000 : Sen. 239680 : Cost 108.27 : Time 153.54s : 13029.10 words/s
[2017-08-02 11:34:34] Ep. 1 : Up. 4000 : Sen. 319680 : Cost 96.53 : Time 151.37s : 13220.71 words/s
[2017-08-02 11:37:05] Ep. 1 : Up. 5000 : Sen. 399680 : Cost 86.97 : Time 150.76s : 13258.95 words/s
[2017-08-02 11:39:38] Ep. 1 : Up. 6000 : Sen. 479680 : Cost 80.35 : Time 153.04s : 13078.83 words/s
[2017-08-02 11:42:10] Ep. 1 : Up. 7000 : Sen. 559680 : Cost 75.62 : Time 152.70s : 13060.32 words/s
[2017-08-02 11:44:43] Ep. 1 : Up. 8000 : Sen. 639680 : Cost 71.12 : Time 152.88s : 13070.99 words/s
[2017-08-02 11:47:15] Ep. 1 : Up. 9000 : Sen. 719680 : Cost 67.28 : Time 152.21s : 13097.38 words/s
[2017-08-02 11:49:47] Ep. 1 : Up. 10000 : Sen. 799680 : Cost 65.04 : Time 151.73s : 13157.16 words/s
```

**Pull request merged**
