### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
graph_->setOptimized/isOptimized is no longer used. This functionality has moved to the Backend, but the methods still exist in the graph_ which always return false
```
grep -R "Optimized("
translator/translator.h:          graph->getBackend()->setOptimized(options_->get<bool>("optimize"));
translator/translator.h:        graph->getBackend()->setOptimized(options_->get<bool>("optimize"));
tests/prod.cpp:        g->getBackend()->setOptimized(false);
tests/prod.cpp:        g->getBackend()->setOptimized(true);
tensors/gpu/backend.h:  // for GPU, this is invalid. for gpu, isOptimized() function always returns false.
tensors/gpu/backend.h:  void setOptimized(bool optimize) override {
tensors/gpu/backend.h:    LOG_ONCE(info, "setOptimized() not supported for GPU_{}", optimize);
tensors/gpu/backend.h:  bool isOptimized() override {
tensors/cpu/backend.h:  void setOptimized(bool optimize) override { optimized_ = optimize; }
tensors/cpu/backend.h:  bool isOptimized() override { return optimized_; }
tensors/backend.h:  // for GPU, this is invalid. for gpu, isOptimized() function always returns false.
tensors/backend.h:  virtual void setOptimized(bool optimize) = 0;
tensors/backend.h:  virtual bool isOptimized() = 0;
rescorer/rescorer.h:        graph->getBackend()->setOptimized(options_->get<bool>("optimize"));
microsoft/quicksand.cpp:  graph->getBackend()->setOptimized(false);
graph/expression_graph.h:  void setOptimized(bool optimized) { optimized_ = optimized; }
graph/expression_graph.h:  bool isOptimized() { return (optimized_ && inferenceOnly_); }
graph/expression_operators.cpp:      if(a->graph()->getBackend()->isOptimized()) {
graph/expression_operators.cpp:      if(a->graph()->getBackend()->isOptimized()) {
command/marian_conv.cpp:  graph->getBackend()->setOptimized(false);
```
This patch removes the unused variable from the graph class.

Cheers,

Nick

### CODE REVIEW

**Comment by emjotde** [comment]
Removing this compiles and everything?

**Comment by XapaJIaMnu** [comment]
Yes.

grep doesn't find a single place in the codebase where graph->*Optimized() is called.

**Comment by snukky** [comment]
Wasn't this related to the autotuner? If so, maybe it can also be removed? (the autotuner required boost::timer, which has already been removed)

**Comment by emjotde** [comment]
OK, this is fine, I keep forgetting we use backend() for this now.

**Pull request merged**
