### PR TITLE
Fix python library path

### PR DESCRIPTION
**Pull request by lparam**

### CODE REVIEW

**Comment by snukky** [comment]
Thanks. This will work with marian repo, but not with marian-dev used solely. 

BTW, if you need s2s in server mode, check `server` command.

**Comment by lparam** [comment]
Do yout mean s2s_server.cpp?

**Comment by snukky** [comment]
Yes. This corresponds to `build/server`.

**Comment by snukky** [comment]
Open a new issue/question at the google group and provide `.npz.json` file. My guess is that you are using a WMT16 Edi model and you probably need `--dim-emb 500`. But that's only a guess.

**Comment by emjotde** [comment]
Are these the en-de models? s2s does not currently recognize model properties for models that have been trained with nematus and now with marian. Here you would need to provide the model parameters:

`~/marian-dev/build/s2s -d 0 -m en-de/model-ens?.npz -v en-de/vocab.en.json en-de/vocab.de.json -i data/newstest2015.ende.en --dim-vocabs 85000 85000  --dim-emb 500`

For a model trained with marian this works automatically. @snukky did we plan to have a script that can do the conversion?

**Comment by lparam** [comment]
Thanks to both of you. 
After adding “--dim-vocabs 85000 85000 --dim-emb 500”, it works fine.

**Pull request closed without merging**
