### PR TITLE
fix model loading on architectures where size_t is 32bits

### PR DESCRIPTION
**Pull request by XapaJIaMnu**
### Description
When porting marian to architectures of different width (x86_32/arm32/wasm) the binary file format would fail to load. The reason for that is that `size_t` on those architectures translates to `uint32_t`, whereas most commonly the binary models are built on `x86_64`. This pull request makes sure that when binary model is loaded or stored, all headers are of type `uint64_t` . This pull request would not change the existing functionality but would make porting to architectures of different width easier, as the programmer would not be facing cryptic errors when loading binary models.

- [ ] I have tested the code manually
- [x] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [x] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by emjotde** [comment]
@snukky do we have any regression tests that use the *.bin models?
Might be time to add a small test that can do something with memory mapping, at least in a unit test.

**Comment by emjotde** [comment]
Let's merge this one first, then we can unit test this PR.
https://github.com/marian-nmt/marian-dev/pull/826

**Comment by emjotde** [comment]
Also, modify the changelog please.

**Comment by snukky** [comment]
> do we have any regression tests that use the *.bin models?

@emjotde We have these that use `.bin` models, plus "wngt19" tests include versions for avx2 and avx512.
```
tests/decoder/intgemm/test_intgemm_16bit_avx2.sh
tests/decoder/intgemm/test_intgemm_16bit.sh
tests/decoder/intgemm/test_intgemm_16bit_sse2.sh
tests/decoder/intgemm/test_intgemm_8bit_avx2.sh
tests/decoder/intgemm/test_intgemm_8bit.sh
tests/decoder/intgemm/test_intgemm_8bit_ssse3.sh
tests/models/wngt19/test_model_base_fbgemm_packed16.sh
tests/models/wngt19/test_model_base_fbgemm_packed8.sh
tests/models/wnmt18/test_student_small_aan_intgemm16.sh
tests/models/wnmt18/test_student_small_aan_intgemm8.sh
```

**Comment by XapaJIaMnu** [comment]
I updated the changelog. As roman said, the regression tests include plenty of binarizations and model loadings and since those past, I think it's fine.

BTW @emjotde  did the big MPI fixes land?

**Comment by emjotde** [comment]
RE: MPI, yes. that was the last sync.

**Comment by emjotde** [comment]
I have to take a look what is going on with binary file loading in general on windows, then this PR should be ready to go in. 
Something seems weird in #826

**Review by snukky — APPROVED** [review]

**Pull request merged**
