### PR TITLE
Fix compile error in gcc10 - include stdexcept

### PR DESCRIPTION
**Pull request by ykim362**
### Description
This fixes compile errors in gcc 10. In gcc10, <stdexcept> needs to be explicitly included. 

This PR fixes a bug #661 .

List of changes:
- FBGEMM commit hash

Added dependencies: none

### How to test
Compile with gcc 10

### Checklist

- [x] I have tested the code manually
- [x] I have run regression tests
- [x] I have read and followed CONTRIBUTING.md
- [ ] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by ykim362** [comment]
Hi @XapaJIaMnu ,
Would you be able to verify this fixes the compile error in gcc10?

**Comment by XapaJIaMnu** [comment]
Partly fixed. This still remains:
```
[ 51%] Building CXX object src/3rd_party/fbgemm/CMakeFiles/fbgemm_avx2.dir/src/FbgemmI8Depthwise3DAvx2.cc.o
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In function ‘void fbgemm::depthwise_3x3x3_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, int32_t, const fbgemm::PackedDepthWiseConvMatrix&, float, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, float, int, int)’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:932:11: error: there are no arguments to ‘logic_error’ that depend on a template parameter, so a declaration of ‘logic_error’ must be available [-fpermissive]
  932 |     throw logic_error(msg);
      |           ^~~~~~~~~~~
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:932:11: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In function ‘void fbgemm::depthwise_3x3x3_per_channel_quantization_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, const int32_t*, const fbgemm::PackedDepthWiseConvMatrix&, const float*, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, const float*, int, int)’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1177:11: error: there are no arguments to ‘logic_error’ that depend on a template parameter, so a declaration of ‘logic_error’ must be available [-fpermissive]
 1177 |     throw logic_error(msg);
      |           ^~~~~~~~~~~
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In instantiation of ‘void fbgemm::depthwise_3x3x3_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, int32_t, const fbgemm::PackedDepthWiseConvMatrix&, float, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, float, int, int) [with BIAS_TYPE = int; int32_t = int; uint8_t = unsigned char]’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1283:18:   required from here
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:932:22: error: ‘logic_error’ was not declared in this scope
  932 |     throw logic_error(msg);
      |           ~~~~~~~~~~~^~~~~
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In instantiation of ‘void fbgemm::depthwise_3x3x3_per_channel_quantization_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, const int32_t*, const fbgemm::PackedDepthWiseConvMatrix&, const float*, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, const float*, int, int) [with BIAS_TYPE = int; int32_t = int; uint8_t = unsigned char]’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1328:18:   required from here
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1177:22: error: ‘logic_error’ was not declared in this scope
 1177 |     throw logic_error(msg);
      |           ~~~~~~~~~~~^~~~~
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In instantiation of ‘void fbgemm::depthwise_3x3x3_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, int32_t, const fbgemm::PackedDepthWiseConvMatrix&, float, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, float, int, int) [with BIAS_TYPE = float; int32_t = int; uint8_t = unsigned char]’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1375:20:   required from here
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:932:22: error: ‘logic_error’ was not declared in this scope
  932 |     throw logic_error(msg);
      |           ~~~~~~~~~~~^~~~~
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc: In instantiation of ‘void fbgemm::depthwise_3x3x3_per_channel_quantization_pad_1(int, int, int, int, int, int, int, int, int32_t, const uint8_t*, const int32_t*, const fbgemm::PackedDepthWiseConvMatrix&, const float*, int32_t, uint8_t*, const int32_t*, const BIAS_TYPE*, bool, const float*, int, int) [with BIAS_TYPE = float; int32_t = int; uint8_t = unsigned char]’:
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1421:20:   required from here
/.../marian-dev-bench/src/3rd_party/fbgemm/src/FbgemmI8Depthwise3DAvx2.cc:1177:22: error: ‘logic_error’ was not declared in this scope
 1177 |     throw logic_error(msg);
      |           ~~~~~~~~~~~^~~~~
```
Thanks!

Nick

**Comment by XapaJIaMnu** [comment]
@ykim362 this fixes the issue on top of your patch:
```cpp
diff --git a/src/FbgemmI8Depthwise3DAvx2.cc b/src/FbgemmI8Depthwise3DAvx2.cc
index 7e12678..807916a 100644
--- a/src/FbgemmI8Depthwise3DAvx2.cc
+++ b/src/FbgemmI8Depthwise3DAvx2.cc
@@ -5,7 +5,7 @@
  * LICENSE file in the root directory of this source tree.
  */
 #include "fbgemm/FbgemmI8DepthwiseAvx2.h"
-
+#include <stdexcept>
 #include <string>
 #include <tuple> // for tie
 
diff --git a/src/FbgemmI8DepthwiseAvx2.cc b/src/FbgemmI8DepthwiseAvx2.cc
index 8e875cc..eff9da1 100644
--- a/src/FbgemmI8DepthwiseAvx2.cc
+++ b/src/FbgemmI8DepthwiseAvx2.cc
@@ -6,7 +6,7 @@
  */
 #include "fbgemm/FbgemmI8DepthwiseAvx2.h"
 #include "fbgemm/Utils.h"
-
+#include <stdexcept>
 #include <string>
 #include <tuple> // for tie
```

**Comment by ykim362** [comment]
Thanks, @XapaJIaMnu. I have pushed a new commit with those two missing stdexcept added. Could you verify and approve this PR?

**Comment by XapaJIaMnu** [comment]
@ykim362 this works, thanks! I don't have approval power though

**Comment by ykim362** [comment]
@emjotde gcc10 and visual studio 2019 require a standard library header (<stdexcept>) to be explicitly included in the code to use function like `logic_error`. This PR updates commit hash of fbgemm with those headers included. Can you please approve this?

**Pull request merged**
