### PR TITLE
C++ source should not have execute bits

### PR DESCRIPTION
**Pull request by kpu**

### CODE REVIEW

**Comment by emjotde** [comment]
I should hold this for a moment, want to check if this will cause merge problems. A couple of bigger ones is coming.

**Comment by emjotde** [comment]
@frankseide would this get in your way somehow?

**Comment by frankseide** [comment]
I have no idea. However, this will keep happening. It is an artefact of Windows and Visual Studio, which somehow keeps messing with the X permissions on Windows, which doesn't have the concept of X permissions. If this does not cause a problem, I suggest to ignore it until VS handles this correctly.

**Comment by emjotde** [comment]
I will pull this in and let's see what happens. Does not seem to cause merge conflicts as no real content has changed.

**Pull request merged**
