### PR TITLE
Add triton custom backend

### PR DESCRIPTION
**Pull request by delong-coder**
### Description
Adding Triton Marian custom backend.

List of changes:
- triton_backend dir

Added dependencies: none

### How to test
Describe how to test your changes, adding command line examples and sample input/output files if relevant.
Point to unit tests or regression tests covering the changes if they have been added.

Describe how you have tested your code, including OS and the cmake command.

### Checklist

- [ ] I have tested the code manually
- [ ] I have run regression tests
- [ ] I have read and followed CONTRIBUTING.md
- [ ] I have updated CHANGELOG.md

### CODE REVIEW

**Comment by DavidLangworthy** [comment]
@delong-coder protobuf is spamming out the PR.   It's hard to see what you actually intend to submit.  Could you remove protobuf even if that means the PR does not compile?  Then we can see what you intend to submit.

**Comment by delong-coder** [comment]
> @delong-coder protobuf is spamming out the PR. It's hard to see what you actually intend to submit. Could you remove protobuf even if that means the PR does not compile? Then we can see what you intend to submit.

Sure.

**Comment by snukky** [comment]
A few quick comments:
* In Marian protobuf is already required for compilation with SentencePiece (`-DUSE_SENTENCEPIECE=on`) and we have it as an external dependency.
* We usually put external libraries into `/src/3rd_party`, ideally as submodules.
* Try not adding binary files into the repository if not really necessary ;)

**Comment by delong-coder** [comment]
Close this PR since the backend is out of date.

**Pull request closed without merging**
