### PR TITLE
Multi-node asynchronous training

### PR DESCRIPTION
**Pull request by tneck**
Non-sparse multi-node asynchronous training. Sparse and sync coming soon.

- Multi-node async graph group header and source (cuda) files
- Changes to CMakeLists.txt and src/CMakeLists.txt to import MPI package and compile the multi-node cuda file
- Option for MultiNodeAsyncGraphGroup in main function (src/command/marian.cpp)
- Command line arguments configuration: --multi-node to enable multi-node training and --multi-node-overlap {1 or 0} to enable or disable communication overlap

- In multi-node training, 'devices' is used to set the device configuration of all nodes in the cluster. It is parsed as follows:
--devices => [num devices node 0] [devices node 0] [num devices node 1] [devices node 1] etc., e.g. --devices 2 0 1 1 0 = node 0 has 2 GPUs, with IDs 0 and 1, and node 1 has 1 GPU, with ID 0

### CODE REVIEW

**Comment by tneck** [comment]
@kpu @XapaJIaMnu @snukky

**Comment by tneck** [comment]
Here's a high level overview of how this works.

[Multi-node-marian-overview.docx](https://github.com/marian-nmt/marian-dev/files/1649593/Multi-node-marian-overview.docx)

**Comment by kpu** [comment]
Paging @afaji as well.

**Comment by snukky** [comment]
I changed the `--devices` option so we can type, for example, `--devices 0:0 1 1:0` (I'll use this for adding `--devices 0-3` or `--devices 0,1,2,3` or other variants later). I also autoformated the code. It's in branch `tneck-master`.

@tneck Is it possible to test multi-node training on Valhalla?

**Comment by tneck** [comment]
@snukky Thanks!

Yes you can test it on Valhalla. I have a copy in the eikthyrnir0 shared directory under my folder (tom).
You can use "mpirun -n <number_of_nodes> --hostfile hosts_mpi -tag-output" then your usual marian command, and use command options "--multi-node" to enable multi-node and "--multi-node-overlap 0" to disable overlapping computation+communication. You probably want to set "disp-freq" to something very low (for testing) because without sparse communication or overlap each mini-batch takes ages. Ensure that the nodes can ssh to each other without password. Also, if you're cloning your own copy, create a file called hosts_mpi that contains on each line a host on which you want to run marian.

**Comment by emjotde** [comment]
@tneck 
This is probably the nicest code we have in Marian. Good job.

**Pull request merged**
